
export type BugSnippet = {
  id: number;
  language: string;
  code: string[];
  buggyLine: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

export const bugList: BugSnippet[] = [
  {
    id: 1,
    language: 'javascript',
    code: [
      'function findMax(arr) {',
      '  let max = 0;',
      '  for (let i = 0; i < arr.length; i++) {',
      '    if (arr[i] > max) {',
      '      max = arr[i];',
      '    }',
      '  }',
      '  return max;',
      '}',
    ],
    buggyLine: 2,
    explanation: 'The initial max value is set to 0. This fails if all numbers in the array are negative. It should be initialized with `arr[0]` or `Number.MIN_SAFE_INTEGER`.',
    difficulty: 'medium',
  },
  {
    id: 2,
    language: 'python',
    code: [
      'def create_multipliers():',
      '    multipliers = []',
      '    for i in range(5):',
      '        multipliers.append(lambda x: i * x)',
      '    return multipliers',
    ],
    buggyLine: 4,
    explanation: 'This is a classic closure issue. The `i` in the lambda is not captured at the time of creation. All lambdas will use the final value of `i` (4). To fix, use a default argument: `lambda x, i=i: i * x`.',
    difficulty: 'hard',
  },
  {
    id: 3,
    language: 'javascript',
    code: [
      'function addItem(arr, item) {',
      '  arr.push(item);',
      '  return arr;',
      '}',
      'const original = ["a", "b"];',
      'const newArray = addItem(original, "c");',
    ],
    buggyLine: 2,
    explanation: 'The function mutates the original array, which can lead to side effects. It should create a new array instead, e.g., `return [...arr, item];`.',
    difficulty: 'easy',
  },
  {
    id: 4,
    language: 'python',
    code: [
        "def add_to_list(value, my_list=[]):",
        "    my_list.append(value)",
        "    return my_list",
    ],
    buggyLine: 1,
    explanation: "Default list arguments are mutable and created only once. The same list is reused across calls. The default should be `None`, and a new list created inside if it's `None`.",
    difficulty: 'medium',
  },
  {
    id: 5,
    language: 'javascript',
    code: [
      'for (var i = 0; i < 5; i++) {',
      '  setTimeout(function() {',
      '    console.log(i);',
      '  }, 100);',
      '}',
    ],
    buggyLine: 1,
    explanation: '`var` is function-scoped, not block-scoped. By the time the timeouts run, the loop is finished and `i` is 5. Using `let` instead of `var` fixes this by creating a new binding for each loop iteration.',
    difficulty: 'hard',
  },
  {
    id: 6,
    language: 'python',
    code: [
      'a = 257',
      'b = 257',
      'if a is b:',
      '  print("This might not print")',
    ],
    buggyLine: 3,
    explanation: 'Python pre-caches integers from -5 to 256. `is` checks for object identity, not value equality. For integers outside this range, Python may create different objects. Use `==` for value comparison.',
    difficulty: 'hard',
  },
  {
    id: 7,
    language: 'javascript',
    code: [
      'const user = { name: "Alex" };',
      'const permissions = { canRead: true };',
      'Object.assign(user, permissions);',
      'permissions.canRead = false;',
    ],
    buggyLine: 3,
    explanation: '`Object.assign` performs a shallow copy. If the properties are objects themselves, only the reference is copied. A deep copy is needed to avoid this mutation.',
    difficulty: 'medium',
  },
  {
    id: 8,
    language: 'python',
    code: [
      'my_list = [1, 2, 3, 4, 5]',
      'for item in my_list:',
      '    if item % 2 == 0:',
      '        my_list.remove(item)',
    ],
    buggyLine: 2,
    explanation: 'Modifying a list while iterating over it can cause items to be skipped. When an item is removed, the indices of subsequent items shift, and the iterator misses the next item.',
    difficulty: 'medium',
  },
  {
    id: 9,
    language: 'javascript',
    code: [
      'const result = "5" + 5;',
    ],
    buggyLine: 1,
    explanation: 'The `+` operator performs string concatenation if one of the operands is a string. The result is "55", not 10. To ensure mathematical addition, explicitly convert the string to a number using `parseInt()` or `Number()`.',
    difficulty: 'easy',
  },
  {
    id: 10,
    language: 'python',
    code: [
      'def get_evens(numbers):',
      '  for n in numbers:',
      '    if n % 2 == 0:',
      '      return n',
    ],
    buggyLine: 4,
    explanation: 'The `return` statement exits the function immediately. To return all even numbers, you should append them to a list and return the list after the loop, or use a generator with `yield`.',
    difficulty: 'easy',
  },
    {
    id: 11,
    language: 'javascript',
    code: [
      'let x = 10;',
      'function showX() {',
      '  console.log(x);',
      '}',
      'function changeX() {',
      '  x = 20;',
      '}',
      'changeX();',
      'showX();',
    ],
    buggyLine: 6,
    explanation: 'This isn\'t a bug, but a concept test. The code prints 20. `showX` accesses the global `x`, which is modified by `changeX` before `showX` is called. It demonstrates scope.',
    difficulty: 'easy',
  },
  {
    id: 12,
    language: 'python',
    code: [
      'import math',
      'radius = "5"',
      'area = math.pi * radius ** 2',
    ],
    buggyLine: 3,
    explanation: 'The `radius` is a string, but mathematical operations require numbers. You need to convert the radius to a number using `int()` or `float()` before calculating the area.',
    difficulty: 'easy',
  },
  {
    id: 13,
    language: 'javascript',
    code: [
      'const arr = [1, 2, 3];',
      'const doubled = arr.map(num => {',
      '  num * 2;',
      '});',
    ],
    buggyLine: 2,
    explanation: 'When using curly braces `{}` in an arrow function, you must use an explicit `return` statement. Otherwise, the function returns `undefined`. The fix is `return num * 2;` or `arr.map(num => num * 2)`.',
    difficulty: 'medium',
  },
  {
    id: 14,
    language: 'python',
    code: [
      's = "hello"',
      's[0] = "H"',
    ],
    buggyLine: 2,
    explanation: 'Strings are immutable in Python. You cannot change a character in a string by index. You have to create a new string, e.g., `s = "H" + s[1:]`.',
    difficulty: 'easy',
  },
  {
    id: 15,
    language: 'javascript',
    code: [
      'console.log(0.1 + 0.2 === 0.3);',
    ],
    buggyLine: 1,
    explanation: 'This is due to floating-point precision errors in binary. 0.1 and 0.2 cannot be represented perfectly, leading to a sum that is not exactly 0.3. Use a tolerance (epsilon) for comparisons.',
    difficulty: 'hard',
  },
  {
    id: 16,
    language: 'python',
    code: [
      'data = {"name": "John", "age": 30}',
      'age = data.get("salary")',
      'print(f"Salary is {age + 5}")',
    ],
    buggyLine: 2,
    explanation: '`.get("key")` returns `None` if the key doesn\'t exist. You cannot perform arithmetic on `None`. Provide a default value, like `data.get("salary", 0)`, to avoid this error.',
    difficulty: 'medium',
  },
  {
    id: 17,
    language: 'javascript',
    code: [
      'const a = [];',
      'if (a) {',
      '  console.log("Array is truthy");',
      '}',
    ],
    buggyLine: 2,
    explanation: 'In JavaScript, empty arrays are "truthy" objects. To check if an array is empty, you must check its `length` property, e.g., `if (a.length > 0)`.',
    difficulty: 'easy',
  },
  {
    id: 18,
    language: 'python',
    code: [
      'def calculate(a, b):',
      '    print(a + b)',
      '',
      'result = calculate(10, 5)',
    ],
    buggyLine: 4,
    explanation: 'The function `calculate` prints the result but does not `return` it. Therefore, `result` is assigned the value `None`, which cannot be used in a mathematical operation.',
    difficulty: 'easy',
  },
  {
    id: 19,
    language: 'javascript',
    code: [
      'const numbers = ["1", "10", "2", "3"];',
      'numbers.sort();',
    ],
    buggyLine: 2,
    explanation: 'By default, `.sort()` sorts elements as strings alphabetically. "10" comes before "2". To sort numerically, you must provide a comparison function like `(a, b) => a - b`.',
    difficulty: 'medium',
  },
  {
    id: 20,
    language: 'python',
    code: [
      'numbers = (1, 2, 3)',
      'numbers.append(4)',
    ],
    buggyLine: 2,
    explanation: '`numbers` is a tuple, which is immutable. You cannot add or remove elements from a tuple. You need to use a list `[]` if you want to modify the collection.',
    difficulty: 'easy',
  },
];
