
export type QuizQuestion = {
  id: number;
  question: string;
  options: string[];
  answer: string;
  category: 'JavaScript' | 'Python' | 'HTML/CSS' | 'General CS' | 'C++';
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

export const quizData: QuizQuestion[] = [
  // JavaScript
  {
    id: 1,
    question: "Which keyword is used to declare a variable that cannot be reassigned?",
    options: ["let", "var", "const", "static"],
    answer: "const",
    category: 'JavaScript',
    explanation: "`const` declares a block-scoped variable, but its value can't be reassigned. `let` is also block-scoped but can be reassigned. `var` is function-scoped.",
    difficulty: 'easy',
  },
  {
    id: 2,
    question: "What does `===` operator check for?",
    options: ["Value only", "Type only", "Value and type", "None of the above"],
    answer: "Value and type",
    category: 'JavaScript',
    explanation: "The strict equality operator `===` checks for both value and type equality without performing type coercion. The `==` operator performs type coercion before comparison.",
    difficulty: 'easy',
  },
  {
    id: 3,
    question: "What is a closure in JavaScript?",
    options: ["A function having access to the parent scope, even after the parent function has closed", "A way to close the browser window", "A built-in data structure", "A type of loop"],
    answer: "A function having access to the parent scope, even after the parent function has closed",
    category: 'JavaScript',
    explanation: "A closure gives you access to an outer function’s scope from an inner function. In JavaScript, closures are created every time a function is created.",
    difficulty: 'hard',
  },
  {
    id: 4,
    question: "Which method is used to add a new element to the end of an array?",
    options: ["shift()", "unshift()", "push()", "pop()"],
    answer: "push()",
    category: 'JavaScript',
    explanation: "`push()` adds one or more elements to the end of an array and returns the new length. `pop()` removes the last element.",
    difficulty: 'easy',
  },
  {
    id: 5,
    question: "What does `NaN` stand for?",
    options: ["Not a Node", "No Available Number", "Not a Number", "New assigned Number"],
    answer: "Not a Number",
    category: 'JavaScript',
    explanation: "`NaN` is a property of the global object. It is a value representing Not-A-Number, which often results from invalid mathematical operations.",
    difficulty: 'easy',
  },
  // Python
  {
    id: 6,
    question: "Which data structure in Python is immutable?",
    options: ["List", "Dictionary", "Set", "Tuple"],
    answer: "Tuple",
    category: 'Python',
    explanation: "Tuples are ordered, immutable collections of objects. Once a tuple is created, you cannot change its values. Lists, dictionaries, and sets are mutable.",
    difficulty: 'medium',
  },
  {
    id: 7,
    question: "What is the output of `print(2 ** 3)`?",
    options: ["6", "8", "9", "5"],
    answer: "8",
    category: 'Python',
    explanation: "The `**` operator in Python is used for exponentiation. `2 ** 3` means 2 raised to the power of 3, which is 8.",
    difficulty: 'easy',
  },
  {
    id: 8,
    question: "How do you start a single-line comment in Python?",
    options: ["//", "/*", "#", "<!--"],
    answer: "#",
    category: 'Python',
    explanation: "In Python, the hash symbol `#` is used to start a single-line comment. Any text after the `#` on that line is ignored by the interpreter.",
    difficulty: 'easy',
  },
  {
    id: 9,
    question: "What is a 'list comprehension' in Python?",
    options: ["A way to create lists using a `for` loop inside `[]`", "A built-in function for sorting lists", "A method to check if an item is in a list", "A special type of list"],
    answer: "A way to create lists using a `for` loop inside `[]`",
    category: 'Python',
    explanation: "List comprehensions provide a concise way to create lists. For example, `[x*x for x in range(5)]` creates `[0, 1, 4, 9, 16]`.",
    difficulty: 'medium',
  },
  {
    id: 10,
    question: "Which keyword is used to define a function in Python?",
    options: ["func", "function", "def", "define"],
    answer: "def",
    category: 'Python',
    explanation: "The `def` keyword is used to create, or define, a function in Python. It is followed by the function name and parentheses.",
    difficulty: 'easy',
  },
  // HTML/CSS
  {
    id: 11,
    question: "What does HTML stand for?",
    options: ["Hyper Text Markup Language", "High-level Text Machine Language", "Hyperlinks and Text Markup Language", "Home Tool Markup Language"],
    answer: "Hyper Text Markup Language",
    category: 'HTML/CSS',
    explanation: "HTML is the standard markup language for documents designed to be displayed in a web browser.",
    difficulty: 'easy',
  },
  {
    id: 12,
    question: "Which CSS property is used to change the background color of an element?",
    options: ["color", "bgcolor", "background-color", "background"],
    answer: "background-color",
    category: 'HTML/CSS',
    explanation: "The `background-color` property specifically sets the background color of an element. The `background` shorthand property can also be used.",
    difficulty: 'easy',
  },
  {
    id: 13,
    question: "What is the CSS 'box model'?",
    options: ["A model for creating 3D shapes", "A box that wraps every HTML element, consisting of: margins, borders, padding, and the actual content", "A JavaScript library for layout", "A type of HTML tag"],
    answer: "A box that wraps every HTML element, consisting of: margins, borders, padding, and the actual content",
    category: 'HTML/CSS',
    explanation: "The CSS box model is a fundamental concept. It's essentially a box that wraps around every HTML element and defines its layout and spacing.",
    difficulty: 'medium',
  },
  {
    id: 14,
    question: "Which HTML tag is used to create a hyperlink?",
    options: ["<link>", "<a>", "<href>", "<p>"],
    answer: "<a>",
    category: 'HTML/CSS',
    explanation: "The `<a>` (anchor) tag is used to create hyperlinks. The `href` attribute within the `<a>` tag specifies the URL of the page the link goes to.",
    difficulty: 'easy',
  },
  {
    id: 15,
    question: "How do you select an element with id 'header' in CSS?",
    options: [".header", "#header", "header", "*header"],
    answer: "#header",
    category: 'HTML/CSS',
    explanation: "In CSS, the hash `#` symbol is used as an ID selector. The period `.` is used for class selectors, and the element name is used for type selectors.",
    difficulty: 'easy',
  },
  // General CS
  {
    id: 16,
    question: "What does 'API' stand for?",
    options: ["Application Programming Interface", "Automated Program Interaction", "Algorithmic Protocol Interface", "Application Process Integration"],
    answer: "Application Programming Interface",
    category: 'General CS',
    explanation: "An API is a set of rules and protocols that allows different software applications to communicate with each other.",
    difficulty: 'easy',
  },
  {
    id: 17,
    question: "Which data structure uses a Last-In, First-Out (LIFO) approach?",
    options: ["Queue", "Stack", "Linked List", "Tree"],
    answer: "Stack",
    category: 'General CS',
    explanation: "A stack is an abstract data type that serves as a collection of elements, with two principal operations: push, which adds an element to the collection, and pop, which removes the most recently added element.",
    difficulty: 'medium',
  },
  {
    id: 18,
    question: "What is the time complexity of a binary search algorithm?",
    options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"],
    answer: "O(log n)",
    category: 'General CS',
    explanation: "Binary search works by repeatedly dividing the search interval in half. This logarithmic time complexity makes it very efficient for searching sorted arrays.",
    difficulty: 'medium',
  },
  {
    id: 19,
    question: "What is 'git'?",
    options: ["A programming language", "A text editor", "A distributed version control system", "A type of server"],
    answer: "A distributed version control system",
    category: 'General CS',
    explanation: "Git is a version control system used for tracking changes in source code during software development. It's designed for coordinating work among programmers.",
    difficulty: 'easy',
  },
  {
    id: 20,
    question: "In object-oriented programming, what is inheritance?",
    options: ["The ability of an object to take on many forms", "A mechanism where a new class inherits properties and behavior from an existing class", "Bundling data and methods that operate on the data into a single unit", "Hiding the internal state and requiring all interaction to be done through an object's methods"],
    answer: "A mechanism where a new class inherits properties and behavior from an existing class",
    category: 'General CS',
    explanation: "Inheritance is a core OOP concept that allows a new class (subclass) to be based on an existing class (superclass), inheriting its attributes and methods.",
    difficulty: 'medium',
  },
   // C++
  {
    id: 21,
    question: "How do you declare a pointer in C++?",
    options: ["ptr<int> p;", "int &p;", "int *p;", "int p*;"],
    answer: "int *p;",
    category: 'C++',
    explanation: "In C++, an asterisk `*` is used after the data type to declare a pointer. `int *p;` declares a pointer `p` that can hold the address of an integer variable.",
    difficulty: 'easy',
  },
  {
    id: 22,
    question: "What is the main difference between a `struct` and a `class` in C++?",
    options: ["Structs cannot have methods", "Class members are public by default, while struct members are private", "Structs are for primitive types only", "Class members are private by default, while struct members are public"],
    answer: "Class members are private by default, while struct members are public",
    category: 'C++',
    explanation: "The only difference is the default access specifier. For a `class`, members are `private` by default. For a `struct`, members are `public` by default.",
    difficulty: 'hard',
  },
  {
    id: 23,
    question: "Which keyword is used to deallocate memory that was allocated with `new`?",
    options: ["free", "remove", "delete", "clear"],
    answer: "delete",
    category: 'C++',
    explanation: "The `delete` operator is used in C++ to release the memory allocated by the `new` operator. For arrays allocated with `new[]`, you must use `delete[]`.",
    difficulty: 'medium',
  },
  {
    id: 24,
    question: "What is function overloading in C++?",
    options: ["Defining multiple functions with the same name but different parameters", "Overriding a function in a derived class", "A function that can call itself", "A function that has too many arguments"],
    answer: "Defining multiple functions with the same name but different parameters",
    category: 'C++',
    explanation: "Function overloading allows you to have multiple functions with the same name, as long as they have a different number of arguments or different types of arguments.",
    difficulty: 'medium',
  },
  {
    id: 25,
    question: "What does STL stand for in C++?",
    options: ["Standard Template Library", "Static Type Language", "System Tool Library", "Standard Transaction Logic"],
    answer: "Standard Template Library",
    category: 'C++',
    explanation: "The STL is a set of C++ template classes to provide common programming data structures and functions such as lists, stacks, arrays, etc.",
    difficulty: 'medium',
  },
  // More questions
   {
    id: 26,
    question: "Which JavaScript framework is known for its virtual DOM?",
    options: ["Angular", "Vue", "React", "Svelte"],
    answer: "React",
    category: 'JavaScript',
    explanation: "React uses a virtual DOM to efficiently update the UI. It keeps a lightweight copy of the real DOM and only updates the parts that have changed.",
    difficulty: 'medium',
  },
  {
    id: 27,
    question: "What is the purpose of the `finally` block in a `try...catch...finally` statement?",
    options: ["To execute code if an error occurs", "To execute code regardless of whether an error occurred or not", "To declare the final value of a variable", "To catch specific types of errors"],
    answer: "To execute code regardless of whether an error occurred or not",
    category: 'JavaScript',
    explanation: "The `finally` block always executes after the `try` and `catch` blocks have completed. It is often used for cleanup code.",
    difficulty: 'medium',
  },
  {
    id: 28,
    question: "What does the `pass` statement do in Python?",
    options: ["It skips the current iteration of a loop", "It terminates the program", "It is a placeholder and does nothing", "It raises an exception"],
    answer: "It is a placeholder and does nothing",
    category: 'Python',
    explanation: "The `pass` statement is a null operation. It is used when a statement is syntactically required but you don't want any command or code to execute.",
    difficulty: 'easy',
  },
  {
    id: 29,
    question: "What is a decorator in Python?",
    options: ["A way to add styling to text", "A function that takes another function and extends its behavior without explicitly modifying it", "A special type of comment", "A variable with a fixed value"],
    answer: "A function that takes another function and extends its behavior without explicitly modifying it",
    category: 'Python',
    explanation: "Decorators are a powerful feature in Python that allow programmers to modify the behavior of a function or class. They are often used for logging, timing, and authorization.",
    difficulty: 'hard',
  },
  {
    id: 30,
    question: "What is the purpose of the `<!DOCTYPE html>` declaration?",
    options: ["It defines the character set of the document", "It is a comment", "It tells the browser that the document is an HTML5 document", "It links to an external stylesheet"],
    answer: "It tells the browser that the document is an HTML5 document",
    category: 'HTML/CSS',
    explanation: "The DOCTYPE declaration is an instruction to the web browser about what version of HTML the page is written in. `<!DOCTYPE html>` is for HTML5.",
    difficulty: 'easy',
  },
  {
    id: 31,
    question: "What is the correct syntax for a `for` loop in C++?",
    options: ["for (i = 0; i < 5; i++)", "for i in 1 to 5", "for (i < 5; i++)", "for (i = 0; i < 5)"],
    answer: "for (i = 0; i < 5; i++)",
    category: 'C++',
    explanation: "The standard C-style for loop syntax includes initialization, condition, and increment/decrement parts within the parentheses.",
    difficulty: 'easy',
  },
  {
    id: 32,
    question: "What is polymorphism?",
    options: ["A type of data structure", "The ability of a message to be displayed in many forms", "A way to store multiple values in one variable", "A feature of object-oriented programming"],
    answer: "The ability of a message to be displayed in many forms",
    category: 'General CS',
    explanation: "Polymorphism allows objects of different classes to respond to the same message (method call) in different ways, which is a core concept in OOP.",
    difficulty: 'medium',
  },
  {
    id: 33,
    question: "Which of the following is NOT a valid CSS selector?",
    options: ["#myId", ".myClass", "$myElement", "div"],
    answer: "$myElement",
    category: 'HTML/CSS',
    explanation: "The '$' symbol is not a standard CSS selector. '#' is for IDs, '.' is for classes, and element names (like 'div') are type selectors.",
    difficulty: 'easy',
  },
  {
    id: 34,
    question: "What will `[1, 2, 3].map(num => num * 2)` return in JavaScript?",
    options: ["[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "[1, 4, 9]", "Error"],
    answer: "[2, 4, 6]",
    category: 'JavaScript',
    explanation: "The `map` method creates a new array by applying a function to each element of the original array. In this case, it doubles each number.",
    difficulty: 'easy',
  },
  {
    id: 35,
    question: "What is the primary purpose of a constructor in Python classes?",
    options: ["To destroy an object", "To initialize the object's state", "To create a copy of the object", "To define the class methods"],
    answer: "To initialize the object's state",
    category: 'Python',
    explanation: "The `__init__` method is the constructor in Python. It's called when a new object is created and is used to set up its initial attributes.",
    difficulty: 'medium',
  },
  {
    id: 36,
    question: "Which of the following data types is not built-in in C++?",
    options: ["int", "string", "float", "char"],
    answer: "string",
    category: 'C++',
    explanation: "`std::string` is part of the C++ Standard Library, not a fundamental built-in type like `int`, `float`, or `char`. You need to include the `<string>` header.",
    difficulty: 'hard',
  },
  {
    id: 37,
    question: "Which data structure is typically used to implement a priority queue?",
    options: ["Stack", "Queue", "Heap", "Linked List"],
    answer: "Heap",
    category: 'General CS',
    explanation: "A Heap is a specialized tree-based data structure that satisfies the heap property, making it ideal for efficiently finding the item with the highest (or lowest) priority.",
    difficulty: 'hard',
  },
  {
    id: 38,
    question: "What does the `flex-grow` property do in CSS Flexbox?",
    options: ["It sets the initial size of a flex item.", "It allows a flex item to grow if there is extra space.", "It allows a flex item to shrink if needed.", "It aligns items along the main axis."],
    answer: "It allows a flex item to grow if there is extra space.",
    category: 'HTML/CSS',
    explanation: "`flex-grow` dictates how much of the remaining space in the flex container should be assigned to the item. A value of 0 means it won't grow.",
    difficulty: 'medium',
  },
  {
    id: 39,
    question: "What is the result of `\"hello\"[1]` in JavaScript?",
    options: ["\"h\"", "Error", "\"e\"", "undefined"],
    answer: "\"e\"",
    category: 'JavaScript',
    explanation: "Strings in JavaScript can be treated like arrays of characters, so bracket notation can be used to access a character at a specific index.",
    difficulty: 'easy',
  },
  {
    id: 40,
    question: "How do you get the number of items in a list in Python?",
    options: ["list.size()", "list.length", "size(list)", "len(list)"],
    answer: "len(list)",
    category: 'Python',
    explanation: "The built-in `len()` function is used to get the number of items in a collection, including lists, tuples, and dictionaries.",
    difficulty: 'easy',
  },
  {
    id: 41,
    question: "What is a 'null pointer exception'?",
    options: ["An error from dividing by zero", "An error from accessing a memory location that doesn't exist", "An error when a program tries to use a reference that points to no object (null)", "An error in the C++ compiler"],
    answer: "An error when a program tries to use a reference that points to no object (null)",
    category: 'General CS',
    explanation: "This common runtime error occurs when you try to access members (like methods or fields) of a variable that hasn't been initialized with an object.",
    difficulty: 'medium',
  },
  {
    id: 42,
    question: "What is the purpose of the `&` symbol in a C++ declaration like `int &ref = x;`?",
    options: ["It declares a pointer", "It gets the memory address of x", "It creates a reference to x", "It performs a bitwise AND operation"],
    answer: "It creates a reference to x",
    category: 'C++',
    explanation: "In a declaration, `&` creates a reference, which is an alias for an existing variable. `ref` and `x` will refer to the same memory location.",
    difficulty: 'medium',
  },
  {
    id: 43,
    question: "Which HTML tag defines the main content of a document?",
    options: ["<main>", "<body>", "<content>", "<article>"],
    answer: "<body>",
    category: 'HTML/CSS',
    explanation: "The `<body>` tag contains all the visible content of an HTML document, such as headings, paragraphs, images, etc. `<main>` is used for the primary content, but it resides within the `<body>`.",
    difficulty: 'easy',
  },
  {
    id: 44,
    question: "What is a 'Promise' in JavaScript?",
    options: ["A guarantee that a function will not have errors", "An object representing the eventual completion or failure of an asynchronous operation", "A type of callback function", "A syntax for declaring variables"],
    answer: "An object representing the eventual completion or failure of an asynchronous operation",
    category: 'JavaScript',
    explanation: "Promises are fundamental for handling asynchronous actions in modern JavaScript, allowing you to chain operations that depend on the result of a previous async task.",
    difficulty: 'hard',
  },
  {
    id: 45,
    question: "What is the difference between a list and a dictionary in Python?",
    options: ["Lists are mutable, dictionaries are not", "Lists are ordered, dictionaries are unordered (in older Python versions)", "Lists use integer indices, dictionaries use keys", "All of the above"],
    answer: "Lists use integer indices, dictionaries use keys",
    category: 'Python',
    explanation: "The primary difference is how they are indexed. Lists are accessed by numerical index (0, 1, 2...), while dictionaries are accessed by a unique key (like a string). Both are mutable.",
    difficulty: 'medium',
  },
  {
    id: 46,
    question: "What does 'TCP/IP' stand for?",
    options: ["Telecommunication Control Protocol/Internet Protocol", "Transmission Control Protocol/Internet Protocol", "Text and Code Protocol/Inter-network Protocol", "Transmission Connection Procedure/Internet Path"],
    answer: "Transmission Control Protocol/Internet Protocol",
    category: 'General CS',
    explanation: "TCP/IP is the foundational suite of communication protocols used to interconnect network devices on the internet.",
    difficulty: 'medium',
  },
  {
    id: 47,
    question: "What is the role of a 'header file' in C++?",
    options: ["It contains the main logic of the program", "It defines function and class declarations that can be shared among multiple source files", "It's where you store comments and documentation", "It is automatically generated by the compiler"],
    answer: "It defines function and class declarations that can be shared among multiple source files",
    category: 'C++',
    explanation: "Header files (`.h` or `.hpp`) are used to declare interfaces (like function prototypes and class definitions) so they can be included and used in different `.cpp` files, promoting modularity.",
    difficulty: 'medium',
  },
  {
    id: 48,
    question: "Which CSS property controls the stacking order of elements?",
    options: ["order", "stack-index", "layer", "z-index"],
    answer: "z-index",
    category: 'HTML/CSS',
    explanation: "`z-index` specifies the stack order of a positioned element. An element with a greater stack order is always in front of an element with a lower stack order.",
    difficulty: 'medium',
  },
  {
    id: 49,
    question: "How do you handle an event in React?",
    options: ["Using addEventListener in the HTML", "By passing a function as a prop like `onClick={myFunction}`", "By using the `<event>` tag", "Events are handled automatically"],
    answer: "By passing a function as a prop like `onClick={myFunction}`",
    category: 'JavaScript',
    explanation: "React has its own event handling system that is very similar to handling events on DOM elements, but with a camelCase naming convention (e.g., `onClick`).",
    difficulty: 'easy',
  },
  {
    id: 50,
    question: "What does the `if __name__ == '__main__':` block do in Python?",
    options: ["It's a mandatory part of every Python script", "It defines the main function", "It allows code to be run only when the file is executed directly, not when imported", "It checks if the script is running on the main server"],
    answer: "It allows code to be run only when the file is executed directly, not when imported",
    category: 'Python',
    explanation: "This is a common Python idiom. The code inside this block will only execute if the script is run as the main program, making it useful for tests or entry points.",
    difficulty: 'hard',
  },
  {
    id: 51,
    question: "What is the purpose of `virtual` keyword in C++?",
    options: ["To declare a function that does not exist", "To enable dynamic dispatch or runtime polymorphism", "To make a variable constant", "To create a virtual memory space"],
    answer: "To enable dynamic dispatch or runtime polymorphism",
    category: 'C++',
    explanation: "The `virtual` keyword on a base class method allows a derived class to provide its own implementation, which will be called even through a base class pointer.",
    difficulty: 'hard',
  },
  {
    id: 52,
    question: "Which algorithm is NOT a sorting algorithm?",
    options: ["Bubble Sort", "Quick Sort", "Dijkstra's Algorithm", "Merge Sort"],
    answer: "Dijkstra's Algorithm",
    category: 'General CS',
    explanation: "Dijkstra's algorithm is used for finding the shortest paths between nodes in a graph. The others are all algorithms for sorting elements in a list.",
    difficulty: 'medium',
  },
  {
    id: 53,
    question: "What is the difference between `let` and `var` in JavaScript?",
    options: ["They are identical", "`let` is function-scoped, `var` is block-scoped", "`let` is block-scoped, `var` is function-scoped", "`var` cannot be reassigned"],
    answer: "`let` is block-scoped, `var` is function-scoped",
    category: 'JavaScript',
    explanation: "`let` and `const` (block-scoped) were introduced in ES6 to solve common problems associated with the function-scoped `var`, like issues in loops.",
    difficulty: 'medium',
  },
  {
    id: 54,
    question: "What is the purpose of the `self` parameter in Python class methods?",
    options: ["It refers to the parent class", "It is a reference to the current instance of the class", "It's an optional parameter for documentation", "It refers to the global scope"],
    answer: "It is a reference to the current instance of the class",
    category: 'Python',
    explanation: "`self` represents the instance of the class. By using `self`, we can access the attributes and methods of the class in Python.",
    difficulty: 'easy',
  },
  {
    id: 55,
    question: "Which of these is used to handle responsive design in CSS?",
    options: ["@media queries", "@responsive rules", "CSS Portals", "The `<responsive>` tag"],
    answer: "@media queries",
    category: 'HTML/CSS',
    explanation: "Media queries are a key part of responsive web design, allowing you to apply different CSS styles for different device characteristics, such as screen width.",
    difficulty: 'easy',
  },
  {
    id: 56,
    question: "What does SQL stand for?",
    options: ["Structured Query Language", "Simple Query Language", "Standardized Query Language", "System Query Logic"],
    answer: "Structured Query Language",
    category: 'General CS',
    explanation: "SQL is a domain-specific language used in programming and designed for managing data held in a relational database management system.",
    difficulty: 'easy',
  },
  {
    id: 57,
    question: "What is the result of `typeof null` in JavaScript?",
    options: ["'null'", "'undefined'", "'object'", "'string'"],
    answer: "'object'",
    category: 'JavaScript',
    explanation: "This is a well-known quirk in JavaScript. The `typeof null` is 'object', which is officially recognized as a mistake that can't be fixed due to backward compatibility issues.",
    difficulty: 'hard',
  },
  {
    id: 58,
    question: "In Python, what does the `yield` keyword do?",
    options: ["It stops the execution of a function entirely", "It creates a generator function", "It returns a value and pauses the function's execution", "Both B and C"],
    answer: "Both B and C",
    category: 'Python',
    explanation: "The `yield` keyword turns a function into a generator. When called, it returns a generator object. It yields a value and pauses execution, saving its state for the next call.",
    difficulty: 'hard',
  },
  {
    id: 59,
    question: "What is the `alt` attribute used for in an `<img>` tag?",
    options: ["To provide alternative text for an image if it cannot be displayed", "To set the alignment of the image", "To link the image to another page", "To define the image's title"],
    answer: "To provide alternative text for an image if it cannot be displayed",
    category: 'HTML/CSS',
    explanation: "The `alt` attribute provides alternative text for screen readers and is displayed if the image fails to load, making web content more accessible.",
    difficulty: 'easy',
  },
  {
    id: 60,
    question: "What is a 'memory leak' in programming?",
    options: ["When a program loses data from memory", "A security vulnerability that exposes memory contents", "When a program fails to release memory that it no longer needs", "When the computer runs out of RAM"],
    answer: "When a program fails to release memory that it no longer needs",
    category: 'General CS',
    explanation: "A memory leak occurs when a program allocates memory but loses the ability to access it, preventing it from being returned to the system, which can degrade performance.",
    difficulty: 'medium',
  },
  {
    id: 61,
    question: "What does the `RAII` acronym stand for in C++?",
    options: ["Resource Acquisition Is Initialization", "Runtime Allocation Is Inheritance", "Recursive Algorithm Iteration Initiative", "Real-time Application Interface"],
    answer: "Resource Acquisition Is Initialization",
    category: 'C++',
    explanation: "RAII is a core C++ programming technique where resource management (like memory or file handles) is tied to object lifetime using constructors and destructors.",
    difficulty: 'hard',
  },
  {
    id: 62,
    question: "What is the `...` syntax called in modern JavaScript?",
    options: ["The dot-dot-dot operator", "The spread/rest operator", "The ellipsis syntax", "The continuation operator"],
    answer: "The spread/rest operator",
    category: 'JavaScript',
    explanation: "The `...` syntax is used as a spread operator to expand iterables (like arrays) into individual elements and as a rest parameter to collect multiple arguments into a single array.",
    difficulty: 'medium',
  },
  {
    id: 63,
    question: "Which of the following is NOT a valid data type in Python?",
    options: ["int", "float", "char", "str"],
    answer: "char",
    category: 'Python',
    explanation: "Python does not have a separate `char` data type. A single character is simply a string of length one.",
    difficulty: 'easy',
  },
  {
    id: 64,
    question: "What does CSS stand for?",
    options: ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"],
    answer: "Cascading Style Sheets",
    category: 'HTML/CSS',
    explanation: "CSS is the language used to describe the presentation of a document written in a markup language like HTML.",
    difficulty: 'easy',
  },
  {
    id: 65,
    question: "What is the primary function of an operating system's kernel?",
    options: ["To provide a user interface", "To manage system resources like CPU, memory, and devices", "To run application software", "To connect to the internet"],
    answer: "To manage system resources like CPU, memory, and devices",
    category: 'General CS',
    explanation: "The kernel is the central component of an operating system that acts as an intermediary between applications and the hardware.",
    difficulty: 'medium',
  },
  {
    id: 66,
    question: "What is a 'template' in C++?",
    options: ["A pre-written function", "A blueprint for creating generic classes or functions", "A type of comment", "A file extension"],
    answer: "A blueprint for creating generic classes or functions",
    category: 'C++',
    explanation: "Templates allow writing generic programs. They enable you to create a single function or a class to work with different data types.",
    difficulty: 'medium',
  },
  {
    id: 67,
    question: "Which method removes the first element from a JavaScript array and returns it?",
    options: ["pop()", "shift()", "slice()", "splice()"],
    answer: "shift()",
    category: 'JavaScript',
    explanation: "The `shift()` method removes the first element from an array and returns that removed element. This method changes the length of the array.",
    difficulty: 'medium',
  },
  {
    id: 68,
    question: "In Python, how can you open a file named 'data.txt' in read mode?",
    options: ["open('data.txt', 'r')", "open.file('data.txt', 'read')", "readFile('data.txt')", "open('data.txt')"],
    answer: "open('data.txt', 'r')",
    category: 'Python',
    explanation: "The `open()` function opens a file. The first argument is the file path, and the second is the mode. 'r' is for reading. Omitting the mode defaults to reading.",
    difficulty: 'easy',
  },
  {
    id: 69,
    question: "What is the difference between `padding` and `margin` in CSS?",
    options: ["They are the same", "Padding is the space inside an element's border; margin is the space outside", "Margin is the space inside an element's border; padding is the space outside", "Padding adds color, margin adds space"],
    answer: "Padding is the space inside an element's border; margin is the space outside",
    category: 'HTML/CSS',
    explanation: "Padding is the space between the content and the border of an element. Margin is the space outside the border, creating separation between elements.",
    difficulty: 'easy',
  },
  {
    id: 70,
    question: "Which of the following is a dynamically-typed language?",
    options: ["C++", "Java", "Python", "C#"],
    answer: "Python",
    category: 'General CS',
    explanation: "In dynamically-typed languages like Python and JavaScript, type checking is performed at runtime, whereas in statically-typed languages like C++ and Java, it's done at compile time.",
    difficulty: 'medium',
  },
  {
    id: 71,
    question: "What is a 'smart pointer' in C++?",
    options: ["A pointer that can point to any data type", "A wrapper class for a raw pointer that provides automatic memory management", "A pointer that is faster than a regular pointer", "A pointer used in AI programming"],
    answer: "A wrapper class for a raw pointer that provides automatic memory management",
    category: 'C++',
    explanation: "Smart pointers like `std::unique_ptr` and `std::shared_ptr` automatically handle memory deallocation, helping to prevent memory leaks.",
    difficulty: 'hard',
  },
  {
    id: 72,
    question: "What is the event loop in JavaScript?",
    options: ["A type of `for` loop", "A mechanism that enables non-blocking asynchronous operations", "A debugging tool", "A way to handle UI events"],
    answer: "A mechanism that enables non-blocking asynchronous operations",
    category: 'JavaScript',
    explanation: "The event loop continuously checks the message queue for new tasks and executes them, allowing JavaScript to perform non-blocking I/O operations despite being single-threaded.",
    difficulty: 'hard',
  },
  {
    id: 73,
    question: "What does the `*args` and `**kwargs` syntax do in Python function definitions?",
    options: ["They are used for pointer arithmetic", "They allow a function to accept a variable number of arguments", "They define required arguments", "They are used for global variables"],
    answer: "They allow a function to accept a variable number of arguments",
    category: 'Python',
    explanation: "`*args` collects extra positional arguments into a tuple, while `**kwargs` collects extra keyword arguments into a dictionary.",
    difficulty: 'medium',
  },
  {
    id: 74,
    question: "Which HTML5 element is used to specify a header for a document or section?",
    options: ["<head>", "<h1>", "<header>", "<section>"],
    answer: "<header>",
    category: 'HTML/CSS',
    explanation: "The `<header>` element is a semantic tag used to define introductory content or navigational links for its containing section or for the whole page.",
    difficulty: 'easy',
  },
  {
    id: 75,
    question: "What is 'Big O' notation used for?",
    options: ["To measure the exact runtime of an algorithm", "To describe the limiting behavior of a function when the argument tends towards a particular value or infinity", "To define object sizes in memory", "To notate large numbers"],
    answer: "To describe the limiting behavior of a function when the argument tends towards a particular value or infinity",
    category: 'General CS',
    explanation: "Big O notation is used in computer science to classify algorithms according to how their run time or space requirements grow as the input size grows.",
    difficulty: 'medium',
  },
  {
    id: 76,
    question: "What is `std::vector` in C++?",
    options: ["A fixed-size array", "A dynamic, contiguous array that can grow or shrink in size", "A type of linked list", "A mathematical vector"],
    answer: "A dynamic, contiguous array that can grow or shrink in size",
    category: 'C++',
    explanation: "`std::vector` is a sequence container from the STL that encapsulates dynamic size arrays, handling memory management automatically.",
    difficulty: 'medium',
  },
  {
    id: 77,
    question: "What is JSON?",
    options: ["A JavaScript-specific notation", "A lightweight data-interchange format", "A styling language for JavaScript", "A database system"],
    answer: "A lightweight data-interchange format",
    category: 'General CS',
    explanation: "JSON (JavaScript Object Notation) is a text-based format for representing structured data. It is language-independent but uses conventions familiar to JavaScript programmers.",
    difficulty: 'easy',
  },
  {
    id: 78,
    question: "What is the purpose of `this` keyword in JavaScript?",
    options: ["It refers to the current HTML document", "It refers to the object from which the function was called", "It refers to the previously called function", "It is a reference to a global object"],
    answer: "It refers to the object from which the function was called",
    category: 'JavaScript',
    explanation: "The value of `this` is determined by how a function is called (its execution context). In a method, it refers to the owner object. In a regular function, it can refer to the global object (window).",
    difficulty: 'medium',
  },
  {
    id: 79,
    question: "What is a 'docstring' in Python?",
    options: ["A type of variable", "A string literal that appears as the first statement in a module, function, class, or method definition", "A multi-line comment", "A documentation file"],
    answer: "A string literal that appears as the first statement in a module, function, class, or method definition",
    category: 'Python',
    explanation: "Docstrings are used to document code. They are accessible at runtime via the `__doc__` attribute and are used by tools like `help()`.",
    difficulty: 'medium',
  },
  {
    id: 80,
    question: "How can you make a list of items with bullet points in HTML?",
    options: ["<ol>", "<ul>", "<dl>", "<list>"],
    answer: "<ul>",
    category: 'HTML/CSS',
    explanation: "The `<ul>` (unordered list) tag is used to create a list of items with bullet points. The `<li>` tag is used for each item within the list.",
    difficulty: 'easy',
  },
  {
    id: 81,
    question: "What is recursion?",
    options: ["A loop that never ends", "A function that calls itself", "A data structure for storing data", "A way to handle errors"],
    answer: "A function that calls itself",
    category: 'General CS',
    explanation: "Recursion is a programming technique where a function solves a problem by calling itself with smaller instances of the same problem until it reaches a base case.",
    difficulty: 'easy',
  },
  {
    id: 82,
    question: "What does the `const` keyword mean when used at the end of a C++ member function declaration?",
    options: ["The function cannot be overridden", "The function returns a constant value", "The function promises not to modify the state of the object", "The function can only be called once"],
    answer: "The function promises not to modify the state of the object",
    category: 'C++',
    explanation: "A `const` member function is one that does not modify any member variables of the object on which it is called. It's a key part of `const`-correctness.",
    difficulty: 'hard',
  },
  {
    id: 83,
    question: "Which of these is a valid way to create an object in JavaScript?",
    options: ["let obj = {}", "let obj = new Object()", "let obj = Object.create(null)", "All of the above"],
    answer: "All of the above",
    category: 'JavaScript',
    explanation: "JavaScript provides multiple ways to create objects: object literal syntax `{}`, the `new Object()` constructor, and `Object.create()` for more advanced inheritance scenarios.",
    difficulty: 'medium',
  },
  {
    id: 84,
    question: "What is a 'set' in Python?",
    options: ["A sorted list of numbers", "An ordered collection of unique items", "An unordered collection of unique items", "A collection that allows duplicate items"],
    answer: "An unordered collection of unique items",
    category: 'Python',
    explanation: "Sets are used to store multiple items in a single variable. They are unordered, unchangeable (though you can add/remove items), and do not allow duplicate values.",
    difficulty: 'medium',
  },
  {
    id: 85,
    question: "What is a 'pseudo-class' in CSS?",
    options: ["A class that doesn't exist", "A keyword added to a selector that specifies a special state of the selected element(s)", "A JavaScript function that mimics a CSS class", "A class with a '#' prefix"],
    answer: "A keyword added to a selector that specifies a special state of the selected element(s)",
    category: 'HTML/CSS',
    explanation: "Pseudo-classes like `:hover`, `:focus`, and `:nth-child()` are used to style elements based on their state or position, which cannot be expressed with simple selectors.",
    difficulty: 'medium',
  },
  {
    id: 86,
    question: "Which data structure is best suited for implementing a cache with a fixed size (like an LRU cache)?",
    options: ["Stack", "A combination of a Hash Map and a Doubly Linked List", "Array", "Binary Tree"],
    answer: "A combination of a Hash Map and a Doubly Linked List",
    category: 'General CS',
    explanation: "A Hash Map provides O(1) lookups for cache items, while a Doubly Linked List allows for O(1) removal/insertion to manage the least recently used items.",
    difficulty: 'hard',
  },
  {
    id: 87,
    question: "What is the purpose of the `iostream` header in C++?",
    options: ["To perform mathematical operations", "To provide basic input and output services", "To work with strings", "To manage memory"],
    answer: "To provide basic input and output services",
    category: 'C++',
    explanation: "The `iostream` library provides objects like `std::cin` for input and `std::cout` for output to the console.",
    difficulty: 'easy',
  },
  {
    id: 88,
    question: "What is 'hoisting' in JavaScript?",
    options: ["Lifting a variable to the top of the file", "The behavior of moving declarations to the top of their scope before code execution", "A way to optimize code performance", "A security feature"],
    answer: "The behavior of moving declarations to the top of their scope before code execution",
    category: 'JavaScript',
    explanation: "In JavaScript, `var` declarations are hoisted to the top of their function scope, and function declarations are hoisted entirely. `let` and `const` are also hoisted but are not initialized.",
    difficulty: 'hard',
  },
  {
    id: 89,
    question: "What is the difference between `==` and `is` in Python?",
    options: ["They are identical", "`==` checks for value equality, `is` checks for object identity", "`is` checks for value equality, `==` checks for object identity", "`is` is used for strings, `==` is for numbers"],
    answer: "`==` checks for value equality, `is` checks for object identity",
    category: 'Python',
    explanation: "`a == b` checks if the values of a and b are the same. `a is b` checks if `a` and `b` point to the exact same object in memory.",
    difficulty: 'medium',
  },
  {
    id: 90,
    question: "Which tag is used to embed a video in an HTML page?",
    options: ["<media>", "<embed>", "<video>", "<movie>"],
    answer: "<video>",
    category: 'HTML/CSS',
    explanation: "The HTML5 `<video>` element is the standard way to embed video content in a web page, with support for attributes like `src`, `controls`, and `autoplay`.",
    difficulty: 'easy',
  },
  {
    id: 91,
    question: "What is a 'race condition'?",
    options: ["A bug in a sorting algorithm", "When two algorithms compete for speed", "A situation where the behavior of a system depends on the sequence or timing of uncontrollable events", "When a computer runs out of memory"],
    answer: "A situation where the behavior of a system depends on the sequence or timing of uncontrollable events",
    category: 'General CS',
    explanation: "Race conditions often occur in concurrent programming when multiple threads or processes access shared data and try to change it at the same time.",
    difficulty: 'hard',
  },
  {
    id: 92,
    question: "What is a destructor in C++?",
    options: ["A function that constructs an object", "A special member function that is called when an object goes out of scope or is deleted", "A tool for debugging memory issues", "A function to delete files"],
    answer: "A special member function that is called when an object goes out of scope or is deleted",
    category: 'C++',
    explanation: "A destructor has the same name as the class, preceded by a tilde (~). It's used to release resources that the object may have acquired during its lifetime.",
    difficulty: 'medium',
  },
  {
    id: 93,
    question: "What does `Array.prototype.reduce()` do?",
    options: ["It reduces the size of an array", "It executes a reducer function on each element of the array, resulting in a single output value", "It creates a new array with a reduced number of elements", "It filters out unwanted elements"],
    answer: "It executes a reducer function on each element of the array, resulting in a single output value",
    category: 'JavaScript',
    explanation: "`reduce()` is a powerful method for summarizing an array's contents into a single value, such as summing numbers or flattening an array of arrays.",
    difficulty: 'medium',
  },
  {
    id: 94,
    question: "Which of these is NOT a core data type in Python?",
    options: ["list", "dict", "array", "tuple"],
    answer: "array",
    category: 'Python',
    explanation: "While Python has an `array` module for handling arrays of a fixed type, it is not a built-in core data type like `list`, `dict`, and `tuple`.",
    difficulty: 'medium',
  },
  {
    id: 95,
    question: "What does the `position: absolute;` CSS property do?",
    options: ["It positions an element relative to its normal position", "It positions an element relative to its nearest positioned ancestor", "It fixes an element relative to the viewport", "It makes an element not take up any space"],
    answer: "It positions an element relative to its nearest positioned ancestor",
    category: 'HTML/CSS',
    explanation: "An absolutely positioned element is removed from the normal document flow and positioned relative to its first non-static ancestor element.",
    difficulty: 'medium',
  },
  {
    id: 96,
    question: "What is a firewall?",
    options: ["A type of computer virus", "A physical barrier to protect servers", "A network security system that monitors and controls incoming and outgoing network traffic", "Software for preventing computer overheating"],
    answer: "A network security system that monitors and controls incoming and outgoing network traffic",
    category: 'General CS',
    explanation: "Firewalls establish a barrier between a trusted internal network and an untrusted external network, such as the Internet, based on a set of security rules.",
    difficulty: 'easy',
  },
  {
    id: 97,
    question: "What is the 'Rule of Three' in C++ (prior to C++11)?",
    options: ["A function should not have more than three arguments", "If a class defines a destructor, it should almost always define a copy constructor and a copy assignment operator", "A program should have at most three classes", "A variable name cannot be longer than three characters"],
    answer: "If a class defines a destructor, it should almost always define a copy constructor and a copy assignment operator",
    category: 'C++',
    explanation: "This is a rule of thumb for resource management. If a class needs a custom destructor, it likely manages a resource that also needs custom copy and assignment logic to avoid issues.",
    difficulty: 'hard',
  },
  {
    id: 98,
    question: "What is CORS?",
    options: ["A JavaScript library", "A security feature that restricts how a resource on a web page can be requested from another domain", "A CSS framework", "A type of HTTP request"],
    answer: "A security feature that restricts how a resource on a web page can be requested from another domain",
    category: 'General CS',
    explanation: "Cross-Origin Resource Sharing (CORS) is a browser security mechanism that prevents a web page from making requests to a different domain than the one that served the page.",
    difficulty: 'medium',
  },
  {
    id: 99,
    question: "Which of these is used for asynchronous programming in Python?",
    options: ["`async/await`", "`threads`", "`promises`", "`callbacks`"],
    answer: "`async/await`",
    category: 'Python',
    explanation: "Modern Python uses the `async` and `await` keywords with the `asyncio` library to write concurrent code in a sequential style.",
    difficulty: 'medium',
  },
  {
    id: 100,
    question: "What is the purpose of the `<html>` tag?",
    options: ["To define the main content", "To represent the root of an HTML document", "To include metadata about the page", "To create a heading"],
    answer: "To represent the root of an HTML document",
    category: 'HTML/CSS',
    explanation: "The `<html>` element is the root element of an HTML page and serves as a container for all other HTML elements (except for the `<!DOCTYPE>` tag).",
    difficulty: 'easy',
  }
];
